"""Mock Stage 2 — architecture fragments and merged Mermaid diagram."""

from __future__ import annotations

import os
import re

from doc_engine.pipeline.mock_stage_constants import (
    _ARCHITECTURE_BUCKETS,
    EM,
)
from doc_engine.pipeline.mock_stage_io import _write_text


def _node_id(relpath, seen):
    base = re.sub(r"[^A-Za-z0-9]", "_", os.path.basename(relpath))
    node = base or "n"
    suffix = 2
    while node in seen:
        node = f"{base}_{suffix}"
        suffix += 1
    seen.add(node)
    return node


def _interesting_paths(pool):
    """Paths that carry architecture-relevant signal buckets."""
    interesting = set()
    for bucket in _ARCHITECTURE_BUCKETS:
        for relpath, _line, _match in pool.get(bucket) or []:
            interesting.add(relpath)
    return interesting


def _group_architecture_files(group, interesting):
    """Prefer interesting files; fall back to a short prefix of the group."""
    files = [path for path in group["files"] if path in interesting]
    if not files:
        files = group["files"][:6]
    return files[:12]


def _fragment_mermaid_lines(group_id, nodes):
    """Build one Mermaid flowchart fragment for a partition group."""
    lines = [
        f"# MOCK architecture fragment {EM} group {group_id}",
        "",
        "Generated by doc_engine.pipeline.local_runner, not by architect-segment.",
        "Node labels are real file names; the edges are adjacency within the",
        "group, not analyzed call flow.",
        "",
        "```mermaid",
        "flowchart TD",
        f"    subgraph group_{group_id}[\"group {group_id}\"]",
    ]
    for relpath, node in nodes:
        lines.append(f"        {node}[\"{os.path.basename(relpath)}\"]")
    lines.append("    end")
    # strict=False: the ragged tail is the point. zip(xs, xs[1:]) is the
    # pairwise-adjacent idiom, so the operands differ in length by one by
    # construction.
    for (_path_a, node_a), (_path_b, node_b) in zip(nodes, nodes[1:], strict=False):
        lines.append(f"    {node_a} --> {node_b}")
    lines.append("```")
    lines.append("")
    return lines


def _write_architecture_fragments(out_dir, groups, interesting, log):
    """Write arch_fragment_<id>.md files; return (group_id, nodes, path) rows."""
    fragments = []
    for group in groups["groups"]:
        group_id = group["id"]
        files = _group_architecture_files(group, interesting)
        seen = set()
        nodes = [(relpath, _node_id(relpath, seen)) for relpath in files]
        path = os.path.join(out_dir, f"arch_fragment_{group_id}.md")
        _write_text(path, "\n".join(_fragment_mermaid_lines(group_id, nodes)))
        fragments.append((group_id, nodes, path))
        log(f"  wrote {os.path.basename(path)} ({len(nodes)} node(s))")
    return fragments


def _append_subgraph_nodes(merged, group_id, nodes):
    """Append one Mermaid subgraph block for a partition group."""
    merged.append(f"    subgraph group_{group_id}[\"group {group_id}\"]")
    for relpath, node in nodes:
        merged.append(f"        {node}[\"{os.path.basename(relpath)}\"]")
    merged.append("    end")


def _cross_group_link(nodes_a, nodes_b):
    """Dotted Mermaid edge between adjacent non-empty groups, or None."""
    if not nodes_a or not nodes_b:
        return None
    return f"    {nodes_a[-1][1]} -.-> {nodes_b[0][1]}"


def _append_cross_group_links(merged, fragments):
    """Link adjacent group subgraphs with dotted edges."""
    # strict=False for the pairwise-adjacent idiom; operands differ by one.
    for (_gid_a, nodes_a, _path_a), (_gid_b, nodes_b, _path_b) in zip(
        fragments, fragments[1:], strict=False
    ):
        link = _cross_group_link(nodes_a, nodes_b)
        if link is not None:
            merged.append(link)


def _merged_architecture_lines(fragments):
    """Assemble architecture_merged.md Mermaid from per-group fragments."""
    merged = [
        f"# MOCK merged architecture {EM} system level",
        "",
        "Generated by doc_engine.pipeline.local_runner, standing in for",
        f"architect-merge over {len(fragments)} fragment(s).",
        "",
        "```mermaid",
        "flowchart TD",
    ]
    for group_id, nodes, _path in fragments:
        _append_subgraph_nodes(merged, group_id, nodes)
    _append_cross_group_links(merged, fragments)
    merged += [
        "```",
        "",
        "## Discrepancies",
        "",
        "None identified. This is a mock merge: no pre-existing README or",
        "architecture document was compared against the diagram above, which is",
        "the comparison architect-merge would actually perform here.",
        "",
    ]
    return merged


def mock_architecture(out_dir, groups, pool, log):
    """arch_fragment_<id>.md per group plus one architecture_merged.md.

    Node labels are real file basenames, never paraphrased — that's
    agents/architect-segment.md rule 3, and test_pipeline_stages.py's
    find_untraceable_nodes() is the mechanical check for it.
    """
    interesting = _interesting_paths(pool)
    fragments = _write_architecture_fragments(out_dir, groups, interesting, log)
    merged_path = os.path.join(out_dir, "architecture_merged.md")
    _write_text(merged_path, "\n".join(_merged_architecture_lines(fragments)))
    log(f"  wrote architecture_merged.md ({len(fragments)} fragment(s) merged)")
    return f"{len(fragments)} fragment(s) + architecture_merged.md"

