"""Core Engine class for the documentation pipeline."""

import json
import sys
import tempfile
from pathlib import Path
from typing import Any, Dict, Optional

from doc_engine.config.settings import Settings
from doc_engine.scanning import scan_repository


class Engine:
    """Public entry point for scan → docs → site."""

    def __init__(self, config: Optional[Settings] = None) -> None:
        self.config = config or Settings()

    def scan(self, repo_path: str, **kwargs: Any) -> Dict[str, Any]:
        cfg = self._effective_config(kwargs)
        allow_codeql = bool(kwargs.get("allow_codeql_build", False))
        return scan_repository(
            repo_path,
            sql_dialect=cfg.sql_dialect,
            respect_gitignore=cfg.respect_gitignore,
            build_command=cfg.build_command,
            db_path=cfg.db_path,
            scanners=cfg.scanners,
            allow_codeql_build=allow_codeql,
        )

    def generate_docs(
        self,
        signals: Dict[str, Any],
        interview_answers: Optional[Dict[str, Any]] = None,
        **kwargs: Any,
    ) -> Dict[str, Any]:
        interview_answers = interview_answers or {}
        docs = _placeholder_docs(signals, interview_answers)
        return {"signals": signals, "docs": docs, "interview_answers": interview_answers}

    def build_site(self, docs_bundle: Dict[str, Any], out_dir: str, **kwargs: Any) -> str:
        from doc_engine.tools.build_docs_site import main as build_site_main

        docs = docs_bundle.get("docs", {})
        with tempfile.TemporaryDirectory() as tmpdir:
            docs_dir = Path(tmpdir) / "docs"
            docs_dir.mkdir()
            for name, content in docs.items():
                (docs_dir / name).write_text(content, encoding="utf-8")

            argv = ["--docs-dir", str(docs_dir), "--out-dir", str(out_dir)]
            for key in ("site_name", "repo_url"):
                if key in kwargs:
                    argv += [f"--{key.replace('_', '-')}", str(kwargs[key])]

            original_argv = sys.argv
            sys.argv = ["build_docs_site.py"] + argv
            try:
                build_site_main()
            finally:
                sys.argv = original_argv

        return str(out_dir)

    def _effective_config(self, overrides: Dict[str, Any]) -> Settings:
        data = self.config.model_dump()
        data.update({k: v for k, v in overrides.items() if v is not None})
        return Settings(**data)


def _placeholder_docs(signals: Dict[str, Any], interview_answers: Dict[str, Any]) -> Dict[str, str]:
    taxonomy = [
        "readme", "architecture", "integrations", "authorization", "database",
        "operations", "observability", "troubleshooting", "configuration",
        "change_impact", "glossary", "local_development", "testing", "known_limitations",
    ]
    entities = sorted(signals.get("entity_table_map", {}).keys())
    docs: Dict[str, str] = {}
    for name in taxonomy:
        docs[f"{name}.md"] = f"# {name.replace('_', ' ').title()}\n\n"
    docs["readme.md"] += (
        f"This documentation was generated by doc_engine.\n\n"
        f"Scanner version: {signals.get('scanner_version', 'unknown')}\n\n"
        f"Entities detected: {len(entities)}\n"
    )
    docs["architecture.md"] += (
        "## Components\n\n" + "\n".join(f"- `{e}`" for e in entities[:20]) + ("\n" if entities else "")
    )
    if interview_answers:
        docs["known_limitations.md"] += (
            "## Interview answers\n\n" + json.dumps(interview_answers, indent=2)
        )
    return docs
